### ISSUE TITLE
Revert changes on checkpatch.pl

### ISSUE THREAD

**Issue by fho** [rtrlib/rtrlib#109]
I couldn't figure out how to reopen a merged issues, so I created this one :-)

Issue is described in https://github.com/rtrlib/rtrlib/pull/97#issuecomment-274027004

> I assume the issue was that the CI failed because checkpatch.pl failed on CHECK:PREFER_KERNEL_TYPES issues.
> 
> We should not modify checkpatch.pl. The checkpatch.pl script is continously improved in the linux kernel. If we change it, it makes it harder to replace our version with a newer one. We would always have to adapt it to our changes again and again.
> 
> If checkpatch.pl complains about something that doesn't make sense in our case, the check can be disabled by passing the "--ignore" parameter to checkpatch.pl, e.g.:
> checkpatch --ignore=PREFER_KERNEL_TYPES

**Comment by mroethke** [comment]
No that is not the issue, the issue is that check level problems should not fail the build, but still show them. That is not possible without patching the script.

Besides we are talking about a 4 line patch that does not modify any existing lines, I doubt that that will cause noteworthy problems during merge of upstream changes.

**Comment by fho** [comment]
For which reported check level problems does it make sense to be shown but not causing the build to fail?

**Comment by smlng** [comment]
IIRC the unittest framework _cmocka_ introduces CamelCase names so that checks fail, which would result travis to fail, too. Another work around would be to exclude respective unittests from coding style checks.

**Comment by fho** [comment]
Yes, or run checkpatch.pl with the corresponding --ignore parameter for that check for all files in tests/unittests/.

**Comment by smlng** [comment]
thought about that, too - I'll add it to #111

**Comment by fho** [comment]
done in #111
