### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#115]
As soon as #114 is done.

**Comment by waehlisch** [comment]
@fho which release number should we assign ;)?

**Comment by waehlisch** [comment]
@smlng can you plesae start extending the CHANGELOG.

**Comment by smlng** [comment]
@waehlisch, okay I'll make a draft and PR today, where we can extend and discuss the changelog

Version should be 0.4.0 for now? I suggest we wait with version 1.0.0 until the new, simple API is ready, too.

**Comment by waehlisch** [comment]
Done in with 3da8b54928b4baa57243e74f6c0c91c3c8d0d243.
