### ISSUE TITLE
Easy installation of RTRlib package: official pkg repos and Launchpad

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#138]
As our RPKI extension was merged into FRR master branch, we want to try again to add RTRlib packages in the official package repositories.

If we don't get it into official repositories soon, we should consider something like Launchpad (see discussion here: https://askubuntu.com/questions/16446/how-to-get-my-software-into-ubuntu).

In any case, we want to have a more easy way for users to install and maintain RTRlib versions.

**Comment by waehlisch** [comment]
@mroethke can you add an RTRlib project to Launchpad that automatically builds and provide RTRlib packages?

**Comment by mroethke** [comment]
I did a little digging, launchpad only supports ubuntu and debian. Open build service(OBS) from the open suse guys supports debian, ubuntu, redhat, centos, archlinux and a few more.

Any objections against OBS?

**Comment by smlng** [comment]
> Any objections against OBS?

Nope, proceed 😉

**Comment by mwinter-osr** [comment]
No problem here, but never used it. Always thought about it being SUSE related (and FRR doesn't support SUSE as nobody really asked about it).
I assume it allows (for Debian) to create a dedicated repo URL for the package similar to launchpad?
(Just publishing packages could be done on github, but the nice thing on Launchpad is to support the "ppa" infrastructure with creating a repo URL for automatic updates)

**Comment by waehlisch** [comment]
@lukas227 takes this over, see http://bugs.debian.org/728206.
