### ISSUE TITLE
Debian Package issues

### ISSUE THREAD

**Issue by mwinter-osr** [rtrlib/rtrlib#140]
I've tried building the debian package. In general, it builds, but has a few issues.
(Sorry, a few minor issues as well - as I spent some time to build a RPM package the same way and some of this didn't make sense)

1) Lintian errors and warnings:

        W: rtrclient: binary-without-manpage usr/bin/rtrclient
        W: cli-validator-dbg: spelling-error-in-description allows to allows one to
        W: cli-validator: spelling-error-in-description allows to allows one to
        W: cli-validator: binary-without-manpage usr/bin/cli-validator
        W: librtr-doc: documentation-package-not-architecture-independent
        W: librtr-doc: embedded-javascript-library usr/share/doc/librtr-doc/html/jquery.js please use libjs-jquery

    I think the errors/warnings should be fixed or overridden (ie with a librtr0.lintian-overrides)

2) I would have expected the main package to be named librtr and not librtr0. Not sure if this is a oversight or expected.

3) How about combining rtrclient and cli-validator in the same package (ie rtr-tools?). Both packages are very small and I would not expect people to only install one of them, but not the other

- Martin

PS: Testing packages as I need them for the FRR integration testing

**Comment by waehlisch** [comment]
Thanks @mwinter-osr!

Regarding 1) I'm not so much in favor of overwriting errors or warnings but we can 

2) @fho do you remember whu the package is called librtr0 instead of librtr?

3) Good idea. @mroethke can you do?

**Comment by mwinter-osr** [comment]
On 1): I agree on not overwriting errors. If they are errors, then they should be fixed, but if you think it's just a false warning (ie on the manpage), then overriding it would be the solution. I think that the "normal" user who builds the package and may not be too familiar should not see errors/warnings which the community knows and counts as "don't care".

PS: Happy to try helping on fixing a few issues once the questions are answered. (And will update the RPM to match it as well)

**Comment by fho** [comment]
> I would have expected the main package to be named librtr and not librtr0. Not sure if this is a oversight or expected.

That is on purpose. The package name of a shared library should include the version from the SONAME. This makes it possible to install the same library in different versions.
See: https://www.debian.org/doc/manuals/maint-guide/advanced.en.html

**Comment by mwinter-osr** [comment]
@fho Thanks for the pointer. Learned something new :-)
(I usually thought the initial version has no number and only newer versions - if incompatible - will have the number attached. ie libssh and libssh2)

Reading this (and others), I do believe I want to follow this example and update the RPM PR #141 to do the same.

**Comment by fho** [comment]
@mwinter-osr 
RedHat/RPMs may have a different naming scheme regarding shared library packages.

**Comment by smlng** [comment]
yes, closing now.
