### ISSUE TITLE
Rename `cli-validator`

### ISSUE THREAD

**Issue by smlng** [rtrlib/rtrlib#149]
One thing that bothered me for a while now is the rather ambiguous name `cli-validator`, IMHO we should rename that to `rtr-validator` or `rpki-validator`, or something similar. But the current name is not very helpful. Specifically, as we currently rework/introduce packaging for Linux distros (#141) and may add man-pages (#145) soon.

What do you think?

**Comment by waehlisch** [comment]
The program does route origin validation: origin-validation or rpki-rov?

**Comment by mroethke** [comment]
origin-validation sounds to vague and I think rpki-rov has to many abbreviations.
How about rpki-origin-validator?

**Comment by waehlisch** [comment]
rpki-origin-validator is a bit too long for my taste.

**Comment by reuteran** [comment]
rpki-validator maybe? It could also use a more verbose interface, it doesn't really tell the user how to  validate something.

**Comment by waehlisch** [comment]
rpki-validator sounds very much like https://github.com/RIPE-NCC/rpki-validator
