### ISSUE TITLE
length validation ROUTER_KEY-type PDUs is probably incorrect

### ISSUE THREAD

**Issue by lolepezy** [rtrlib/rtrlib#163]
Hello,

I have the following problem using rtrclient. Whenever I send a PDU of the type ROUTER_KEY I get back an error saying "corrupt data received, length value in PDU is too small?". I did some debugging and found out the following.

The code below defines pdu_router_key to be of the size 4+4+20+4+91=123 bytes. 
... 
#define SKI_SIZE 20 
#define SPKI_SIZE 91 
... 
struct pdu_router_key { 
    uint8_t ver; 
    uint8_t type; 
    uint8_t flags; 
    uint8_t zero; 
    uint32_t len; 
    uint8_t ski[SKI_SIZE]; 
    uint32_t asn; 
    uint8_t spki[SPKI_SIZE]; 
}; 
... 

Also, the function rtr_pdu_check_size has the following code to check the PDU validity:
    if (sizeof(struct pdu_router_key) == pdu->len)
       ....

Apparently due to the memory alignment, sizeof(struct pdu_router_key) == 124, while length of the PDU calculated according to the RFC https://tools.ietf.org/html/draft-ietf-sidr-rpki-rtr-rfc6810-bis-09#section-5.1 is supposed to be 123. 

Could you fix the validation code so that it doesn't reject properly formatted PDUs?

**Comment by mroethke** [comment]
I am somewhat fuzzy where the 91 bytes come from, but assuming that the length of the individual fields is correct #164 should fix this.

Can you confirm?

**Comment by lolepezy** [comment]
It works now, thanks!
