### ISSUE TITLE
Improve doxygen generation

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#168]
Generate Doxyfile using CMake FindDoxygen, see https://cmake.org/cmake/help/v3.12/module/FindDoxygen.html

**Comment by mroethke** [comment]
The relevant doxygen_add_docs function was added in version 3.9 but we have to support older versions because of frr.
However the relevant issue regarding out of tree build was fixed last December with d715e99a6b4633c0af28d32625197673599a68a8.

**Comment by waehlisch** [comment]
Fixed in #146.
