### ISSUE TITLE
Error Diagnostic Message expected to end with NUL char

### ISSUE THREAD

**Issue by pcarana** [rtrlib/rtrlib#234]
### Description
The _Arbitrary Text of Error Diagnostic Message_ within an Error Report PDU is expected to end with a NUL character.

### Steps to reproduce the issue

The RTRlib version and configuration utilized is [rtrclient tool](https://github.com/rtrlib/rtrlib/wiki/Usage-of-the-RTRlib#connect-to-an-rtr-server). The cache server its still under development.

To reproduce the error, the cache server just has to send an Error Report PDU with an _Arbitrary Text of Error Diagnostic Message_ and a _Length of Error Text_ with the exact length of the text. Just to clarify, lets use an example.

The cache server will send an error including the text "Foo", so the length of the text will be 3. When this is received at the client, the client handles the received PDU as a corrupt PDU, since (apparently) is expecting that a NUL character its included at the end of the text and that the length of the text should equals 4.

### Expected results

The error message should be treated as a correct message, since the _Length of Error Text_ is valid. There's nothing at RFC 6810 ([section 5.10](https://tools.ietf.org/html/rfc6810#section-5.10)) and RFC 8210 ([section 5.11](https://tools.ietf.org/html/rfc8210#section-5.11)) specifying that the text must be NUL terminated and that such character must be counted in the Length of Error Text.

### Actual results

The received PDU is treated as a corrupt PDU and the client closes the connection. Using debug the following messages are printed:
```
(2019/05/15 20:43:54:360613): RTR Socket: Error msg is not null terminated!
(2019/05/15 20:43:54:360623): RTR Socket: Received malformed PDU!
(2019/05/15 20:43:54:360629): RTR Socket: corrupt PDU received
(2019/05/15 20:43:54:360635): RTR Socket: Don't send errors for erroneous error PDUs
(2019/05/15 20:43:54:360641): RTR_MGR: Group(1) status changed to: RTR_MGR_ERROR
RTR-Socket changed connection status to: RTR_ERROR_FATAL, Mgr Status: RTR_MGR_ERROR
(2019/05/15 20:43:54:360658): RTR_MGR: No other inactive groups found
(2019/05/15 20:43:54:360663): RTR Socket: State: RTR_ERROR_FATAL
(2019/05/15 20:43:54:360702): TCP Transport(::1:8323): Socket closed
(2019/05/15 20:43:54:360710): RTR_MGR: Group(1) status changed to: RTR_MGR_ERROR
RTR-Socket changed connection status to: RTR_CONNECTING, Mgr Status: RTR_MGR_ERROR

```

### Versions

OS: Ubuntu 18.04.2 LTS
Build environment: GCC

**Comment by mroethke** [comment]
I think you are right.
Thank you.

**Comment by mroethke** [comment]
@pcarana can you test with #235 applied? (I know that tests are failing right now, please try anyway)

**Comment by pcarana** [comment]
Thanks for the quick reply! I've downloaded and tested the update, now it seems fine.

The error message length and content are now valid at the client.
