### ISSUE TITLE
rtr lib support for VRF

### ISSUE THREAD

**Issue by pguibert6WIND** [rtrlib/rtrlib#246]
### Description
This use case happens with frrouting, when operating with vrf netns mode.

Today, rpki operates over backbones,
and for most of frr configuration, creating a main core instance is enough
however, there are cases where the user may map the backbone with a bgp vrf instance.
I work specifically with vrf with vrf backend = network namespaces.
so based on this, it should be possible that a rpki is configured on an IP that is on a specific vrf
practically, without modifications, rtr lib does the following:
rtrlib will attempt to create a socket without taking into account the network namespace.
so if your ip mappings are located in vrf <>, rpki will fail
because the IP rpki tries to reach will not be available.
the attempt is to:
-  create a vrf api on rtrlib so that frr will configure it if needed
- inside rtrlib, use apis so as to create sockets and get address information in the appropriate network namespace

**Comment by pguibert6WIND** [comment]
Hello everyone,
now that https://github.com/rtrlib/rtrlib/pull/252 has been pushed in, is there some process now to officialise delivery of rtr lib to distros ?

**Comment by mroethke** [comment]
I will start preparing a release as soon as #260  and #256 are reviewed and merged. When the new version is released we can ping the packagers.

**Comment by mroethke** [comment]
I just pushed a release containing #252

**Comment by pguibert6WIND** [comment]
thanks a lot !
