### ISSUE TITLE
default expire_interval should be 2*refresh_interval

### ISSUE THREAD

**Issue by sigpipe** [rtrlib/rtrlib#26]
rtr_init() sets expire_interval to 0.5\*refresh_interval when the caller specifies 0 for the expire_interval.  It looks like the intent was 2\*refresh_interval, because the docs for that function match what is specified in RFC6810.

**Comment by nbars** [comment]
Thanks for reporting the issue.

**Comment by waehlisch** [comment]
Literally the bis draft says 
```
Minimum allowed value:  600 seconds (ten minutes).
Maximum allowed value:  172800 seconds (two days).
Recommended default:  7200 seconds (two hours).
```

Let me check with Rob.
