### ISSUE TITLE
Group Shutdown

### ISSUE THREAD

**Issue by Jaykov-s** [rtrlib/rtrlib#267]
Hi, while using the example I notice that when the most preferable group had a connection error,
and the second group start and connect, when the most preferable group connection restored the second group
is shutdown and cannot start again.

I look on the code and notice that you prevent from the group to run again after shutdown:

void *rtr_fsm_start(struct rtr_socket *rtr_socket)
{
    if (rtr_socket->state == RTR_SHUTDOWN)
        return NULL;
...

Why when group connected and shutdown it cannot start again?

Yakov S.

**Comment by mroethke** [comment]
Thanks for the report. I can confirm this bug.

I will try to have a fix for this in the next week or so.
