### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jaykov-s** [rtrlib/rtrlib#271]
Hi, I add the last fix of issue #269 and in a while we got a crashed.
In the LOG file you can see that the cause it assert on the function: tcp_transport.c:99: tr_tcp_open

I attach my source code, the modified files and the crash log.

Jaykovs.

[rtrlib-crash-2022-01-09.log](https://github.com/rtrlib/rtrlib/files/7835891/rtrlib-crash-2022-01-09.log)
[rtr_static.c.txt](https://github.com/rtrlib/rtrlib/files/7835892/rtr_static.c.txt)
[rtr_mgr.c.txt](https://github.com/rtrlib/rtrlib/files/7835899/rtr_mgr.c.txt)
[rtr_mgr.h.txt](https://github.com/rtrlib/rtrlib/files/7835900/rtr_mgr.h.txt)

**Comment by Jaykov-s** [comment]
Hi, I investigate the assert issue that appear after the last mutex deadlock fix and found why we got the assert on the socket connection. I attach the sources, session log file, session xml log file and log with my comments.

I recreate again session with the follow 8 groups:
1. existing local server address: 10.1.68.191, port: 8282, preference: 1
2. existing local server address: 10.1.68.134, port: 8282, preference: 2
3. dummy server address: 1.1.1.1, port 1111, preference: 3
4. dummy server address: 2.2.2.2, port 2222, preference: 4
5. dummy server address: 3.3.3.3, port 3333, preference: 5
6. dummy server address: 4.4.4.4, port 4444, preference: 6
7. dummy server address: 5.5.5.5, port 5555, preference: 7
8. dummy server address: 6.6.6.6, port 6666, preference: 8

In the Log file that include, we can see the scenario that cause the assert,
Server 1 and 2 was up and then both server 1 and 2 was down and restored, I added the follow comments to the log file (rtrlib-crash-issue-2022-01-16-comments.log)

1. Thread-1 (Group-1) Open TCP Connection and Connection refused. (line: 41160)
2. Thread-2 (Group-2) Open TCP Connection and Connection refused. (line: 41163)
3. Thread-1 (Group-1) Run the function: is_some_rtr_mgr_group_established. (line: 41172)
4. Thread-2 (Group-2) Run the function: is_some_rtr_mgr_group_established. (line: 41175)
5. Thread-1 (Group-1) Run the function: get_best_inactive_rtr_mgr_group. (line: 41179)
6. Thread-2 (Group-2) Run the function: get_best_inactive_rtr_mgr_group. (line: 41183)
7. Thread-1 (Group-1) Got best inactive group - group 4 and start it thread (thread-4) (line :41188)
8. Thread-2 (Group-2) Got best inactive group - group 4 again and start thread-4 again. (line: 41191)
9. Thread-4-1 (Group-4) Start FSM and open socket connection. (line: 41195)
10. Thread-4-2 (Group-4) Start FSM and open socket connection, in this state there is two thread-4 that running. (line: 41198)
11. In a while thread 4-1 open socket connection and try to connect so the socket is now not equal to -1, (4). (line: 41403)
12. thread 4-2 open the same socket and it value euqal to 4 so we got the assertion and the system crashed. (line: 41409)

[rtrlib-crash-issue-2022-01-16.log](https://github.com/rtrlib/rtrlib/files/7877368/rtrlib-crash-issue-2022-01-16.log)
[rtrlib-crash-issue-2022-01-16-comments.log](https://github.com/rtrlib/rtrlib/files/7877369/rtrlib-crash-issue-2022-01-16-comments.log)
[rtrlib-crash-issue-2022-01-16.xml.txt](https://github.com/rtrlib/rtrlib/files/7877370/rtrlib-crash-issue-2022-01-16.xml.txt)
[rtr_static.c.txt](https://github.com/rtrlib/rtrlib/files/7877371/rtr_static.c.txt)
[rtr.c.txt](https://github.com/rtrlib/rtrlib/files/7877372/rtr.c.txt)
[rtr_mgr.c.txt](https://github.com/rtrlib/rtrlib/files/7877373/rtr_mgr.c.txt)
[rtr_mgr.h.txt](https://github.com/rtrlib/rtrlib/files/7877374/rtr_mgr.h.txt)
[tcp_transport.c.txt](https://github.com/rtrlib/rtrlib/files/7877375/tcp_transport.c.txt)
[tcp_transport.h.txt](https://github.com/rtrlib/rtrlib/files/7877376/tcp_transport.h.txt)

**Comment by mroethke** [comment]
Thanks!

I think this bug was "uncovered" by #268 and is caused a lack of locking, I will look into a fix in the next days.

**Comment by Jaykov-s** [comment]
@mroethke I combine your code from issue #270 & #271 and now it's seem that the system working without any assert or mutex deadlock. Thank you very much,
Jaykovs
