### ISSUE TITLE
Use a sane coding style: kernel coding style

### ISSUE THREAD

**Issue by fho** [rtrlib/rtrlib#3]
Convert all sources files to use kernel coding style.
https://www.kernel.org/doc/Documentation/CodingStyle

**Comment by smlng** [comment]
Consistent code style would be great, and the kernel coding style is fine. Except for on thing, I would recommend to use typedef for structs and enums. IMHO this would enhance readability and reduce length of statements.

**Comment by waehlisch** [comment]
They have been removed in PR #8. @fho comments?

**Comment by smlng** [comment]
Yes I see - maybe there is no right or wrong here. So can we find rough consensus on this: do we want to apply _strict_ kernel coding style or revert to/opt for _better_ readability?

Further, in [rtrlib/rtr/packets.c](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c) there are lots of _enums_ and _structs_ defined which should be moved to the corresponding header file - or is there any viable reasoning to have these in the C-file?

We could/should apply some code style checker such as [indent](http://www.gnu.org/software/indent/).

**Comment by fho** [comment]
Hello Matthias and Sebastian :-)

> Yes I see - maybe there is no right or wrong here. So can we find rough consensus on this: do we want to apply strict kernel coding style or revert to/opt for better readability?

I would go with the full Kernel coding style, without our own extra rules.

The Kernel Coding Style Guide argues regarding better readability when typedefs are used:
> Chapter 5: Typedefs
> 
> Please don't use things like "vps_t".
> It's a _mistake_ to use typedef for structures and pointers. When you see a
> 
> 	vps_t a;
> 
> in the source, what does it mean?
> In contrast, if it says
> 
> 	struct virtual_container *a;
> 
> you can actually tell what "a" is.
> 
> Lots of people think that typedefs "help readability". Not so. They are
> useful only for: [..]
https://www.kernel.org/doc/Documentation/CodingStyle

If the user wants to have typedefs, he could also declare them on his own.

> Further, in rtrlib/rtr/packets.c there are lots of enums and structs defined which should be moved to the corresponding header file - or is there any viable reasoning to have these in the C-file?
They are in the .c file because they have a private scope. They are only used by the code in that file. They are not intended to be used by other code parts.k

> We could/should apply some code style checker such as indent.
Indent is sadly not enough to convert to kernel coding style. 
Because the code is often nested very deeply,  the 80-characters per line limit (especially with 8 spaces per tab) is not met after automatic reformatting.
The code has to be restructured manually. The deep level of nesting has to be reduced by moving fragments to seperate functions.
Also declarations have to be moved to beginning of blocks manually.

**Comment by smlng** [comment]
To push this initiative, maybe we should enforce coding style on PRs that introduce changes to any source file?
