### ISSUE TITLE
./tools/rtrclient ssh and valgrind's Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by shaddeus** [rtrlib/rtrlib#31]
Hi,

I am playing with RTRLib SSH transfer mode. It works great!
However I detected with valgrind some warnings 'Conditional jump or move depends on uninitialised value(s)' while I testing with ./tools/rtrclient from RTRLib.

See:
http://www.file-upload.net/download-10968936/valgrind_log.txt.html
(While uploading file at github, I got "Something went really wrong, and we can’t process that file.")

It looks like the problem is somewhere in the libcrypto.so. Do you have ever seen this?

I used the latest RTRLib version from the master branch: f0eca8b
I used the rpki-rtr from (http://rpki.net/) as the rtr cache server.

Is the problem in the RTRLib or in the libcrypto.so?

Best wishes,
Pavel

**Comment by waehlisch** [comment]
Thanks for letting us know! We will have a more detailed look soon.But it seems that it's not a problem in the RTRlib.
