### ISSUE TITLE
/root/quagga-rtrlib/bgpd/bgp_rpki_commands.c:273: undefined reference to `tr_ssh_init'

### ISSUE THREAD

**Issue by wijethunge** [rtrlib/rtrlib#42]
Hi Team

I'm experiencing below error when I hit make on the package, could you guys please help me with this as early as possible 

libtool: link: gcc -fPIE -Os -fno-omit-frame-pointer -g -std=gnu99 -Wall -Wsign-compare -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wmissing-prototypes -Wmissing-declarations -Wchar-subscripts -Wcast-qual -pthread -pie -rdynamic -o .libs/bgpd bgp_main.o  libbgp.a ../lib/.libs/libzebra.so -lm -lcrypt -lrt -lrtr -pthread
libbgp.a(bgp_rpki_commands.o): In function `add_ssh_cache':
/root/quagga-rtrlib/bgpd/bgp_rpki_commands.c:273: undefined reference to `tr_ssh_init'
collect2: error: ld returned 1 exit status
make[2]: *** [bgpd] Error 1
make[2]: Leaving directory `/root/quagga-rtrlib/bgpd'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/quagga-rtrlib'
make: *** [all] Error 2

Thanks in advance

**Comment by waehlisch** [comment]
Did you install libssh?
Can you be more specific which command you run.

**Comment by wijethunge** [comment]
Hi

I have referred below url

git://github.com/rtrlib/quagga-rtrlib.git



On Mon, Nov 23, 2015 at 9:06 PM, Matthias Wählisch <notifications@github.com

**Comment by waehlisch** [comment]
@wijethunge please use the branch https://github.com/rtrlib/quagga-rtrlib/tree/temporary/rebase

**Comment by wijethunge** [comment]
hey

sorry for the trouble, can you please guide me trough installation steps to
follow through, because I'm still new to this..

Thanks in advance..

**Comment by waehlisch** [comment]
After you have installed libSSH and RTRlib:
```
git clone https://github.com/rtrlib/quagga-rtrlib.git
cd quagga-rtrlib
git checkout temporary/rebase
./update-autotools && autoreconf
./configure --enable-rpki
make && make install
```

**Comment by wijethunge** [comment]
does all should have to be on the same path ?

what is the best path to install this?

is it ok olif I proceed with latest ubuntu LTS version?

Thanks a lot for your kind cooperation..

cheers

**Comment by waehlisch** [comment]
Where to install depends on you. Easiest way is to use default paths (/usr/local/...).
Latest Ubuntu LTS should be fine.

**Comment by wijethunge** [comment]
is it libssh-dev ? or just libssh?

**Comment by waehlisch** [comment]
libssh-dev

**Comment by wijethunge** [comment]
Hi

Sorry for the trouble, is below method correct for rtrlib installation ?

*# cd / usr / src*
*#wget **https://github.com/rtrlib/quagga-rtrlib.git
<https://github.com/rtrlib/quagga-rtrlib.git>*
#cd rtrlib
Release #cmake D = D CMAKE_BUILD_TYPE LIBSSH_LIBRARY = / usr / lib /
i386-linux-gnu / libssh.so LIBSSH_INCLUDE D = / usr / lib / i386-linux-gnu.
#make
#make install

**Comment by waehlisch** [comment]
No.
```
wget https://github.com/rtrlib/rtrlib/archive/master.zip
cd rtrlib-master
cmake -D CMAKE_BUILD_TYPE=Release .
make
make install
cd ..
git clone https://github.com/rtrlib/quagga-rtrlib.git
cd quagga-rtrlib
git checkout temporary/rebase
./update-autotools && autoreconf
./configure --enable-rpki
make && make install
```

**Comment by wijethunge** [comment]
Thanks a lot I will try right away...

Thanks again

On Tue, Nov 24, 2015 at 6:32 PM, Matthias Wählisch <notifications@github.com

**Comment by wijethunge** [comment]
Hi

Thanks to you all got installed

But still I couldn't telnet 127.0.0.1 bgpd

Is there additional steps me to follow on ?

**Comment by wijethunge** [comment]
Hi

I just only needs to run bgpd service

Thanks in advance

**Comment by wijethunge** [comment]
Hi

May thanks if you can confirm this steps are correct me to follow in bgpd
installation and ncc validation

#adduser quagga
#echo "/usr/local/lib/i386-linux-gnu" >> /etc/ld.so.conf
#ldconfig
#cd /usr/local
#chown -R quagga.quagga etc/
#echo "password test" > /usr/local/etc/bgpd.conf
#cd/usr/local/sbin
#./bgpd &
#ps -ef | grep bgpd
#telnet localhost bgpd  (deberias obtener un prompt, password test)

**Comment by waehlisch** [comment]
Actually, these problems are independent of the RTRlib.
What is the output of "ps -aux | grep -i bgpd"? If there is no process running, telnet will fail.
If the projects is running, you can check if the daemon listens on the correct port "netstat -an | grep 2605"

**Comment by wijethunge** [comment]
Hey Boss

Everything is working perfect, thanks for your grate support, i have one
last question to trouble you

I have configured bgpd as below by referring an article

#adduser quagga
#echo "/usr/local/lib/i386-linux-gnu" >> /etc/ld.so.conf
#ldconfig
#cd /usr/local
#chown -R quagga.quagga etc/
#echo "password test" > /usr/local/etc/bgpd.conf
#cd/usr/local/sbin
#./bgpd &
#ps -ef | grep bgpd
#telnet localhost bgpd

Everything worked perfect till I restart the server

each time I have to run "./bgpd &" and cannot save configurations on
router, I'm getting below error

Can't backup old configuration file /usr/local/etc/bgpd.conf.sav.

Could you please help me to resolve above ? , then I'm done with this

Thank you so much for your grate support.

Have grate day!!!

Thanks
Thanushka,



On Tue, Nov 24, 2015 at 7:34 PM, Matthias Wählisch <notifications@github.com

**Comment by waehlisch** [comment]
I suppose that you don't have write access. Check /usr/local/etc/ or the file /usr/local/etc/bgpd.conf.sav

**Comment by wijethunge** [comment]
Hi

I got another question could you please help me ?

How can I get bgpd routing table to my ubuntu routing table ?

On Wed, Nov 25, 2015 at 8:58 PM, Matthias Wählisch <notifications@github.com

**Comment by wijethunge** [comment]
I really need your help and advice on this, please..

**Comment by wijethunge** [comment]
Hi

Please find the two routing tables below

###BGP

rpki-VirtualBox# sh ip bgp
BGP table version is 0, local router ID is 10.1.1.1
Status codes: s suppressed, d damped, h history, * valid, > best, =
multipath,
              i internal, r RIB-failure, S Stale, R Removed
Origin codes: i - IGP, e - EGP, ? - incomplete
RPKI codes: V valid, I invalid, N not found


    Network          Next Hop            Metric LocPrf Weight Path
N*> 10.0.2.0/24      0.0.0.0                  0         32768 i
N*  10.1.1.0/24      10.1.1.2                 0             0 65001 ?
N*>                  0.0.0.0                  0         32768 i
N*> 10.2.2.0/24      0.0.0.0                  0         32768 i
N*> 10.2.3.0/29      10.2.2.2                               0 65002 28000 ?
N*  200.7.84.0       10.2.2.2                               0 65002 28000 ?
N*>                  10.1.1.2                 0             0 65001 ?

Total number of prefixes 5

###LOCALroot@rpki-VirtualBox:/usr/local/sbin# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use
Iface
default         *               0.0.0.0         U     1002   0        0 eth0
10.0.2.0        *               255.255.255.0   U     0      0        0 eth1
10.1.1.0        *               255.255.255.0   U     0      0        0 eth2
10.2.2.0        *               255.255.255.0   U     0      0        0 eth3
link-local      *               255.255.0.0     U     0      0        0 eth0
link-local      *               255.255.0.0     U     1000   0        0 eth2

**Comment by waehlisch** [comment]
I highly recommend that you read http://www.nongnu.org/quagga/docs/docs-info.html
The Zebra daemon, which is part of Quagga, handles the exchange between Quagga routes and Linux kernel routing table.
