### ISSUE TITLE
Improve CI and automatic testing

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#47]
- [x] Compiling w/ and w/o SSH in Travis
- [x] Integrate outcome of tests/ into Travis
- [x] Add test function in tests/, which validates against live RTR cache (probably not possible with Travis?)

 

For automatic testing of live data we can verify against the ROA configuration for the RIS beacons, see https://www.ripe.net/analyse/internet-measurements/routing-information-service-ris/current-ris-routing-beacons

**Comment by smlng** [comment]
Compiling with SSH in Travis is possible (just install libssh-dev as a dependency), but why bother compiling _without_ SSH? Failures in non-ssh code parts will be found either way.

Each Travis build environment (VM) has network access, so running live validation tests should be possible, too.

**Comment by waehlisch** [comment]
If (for whatever reasons) SSH is not found, RTRlib might successfully compile w/o SSH. The we assume everything is fine, even though SSH compilation has not been checked.

**Comment by smlng** [comment]
All points are addressed (and fullfilled) by PR #58

**Comment by smlng** [comment]
We can close this one, as soon as PR #58 is merged?
