### ISSUE TITLE
Python Binding

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#72]
Provide binding for RTRlib in Python + docu.

**Comment by mroethke** [comment]
Hi,

I am working on a python binding for rtrlib. It can be found [here](https://github.com/mroethke/rtrlib-python).


Currently only basic validation is supported and only one socket can be used.

I reimplemented the cli-validator and the rtrclient in python to provide some examples, you can find them in the tools directory.

If you have any comments or questions please fire away :)

**Comment by smlng** [comment]
With [this](https://github.com/rtrlib/python-binding) available, the issue is resolved. Big thanks to @mroethke 👏
