### ISSUE TITLE
Debian package requires libssh

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#73]
It seems that the Debian package requires libssh. We should be more relaxed. If a libssh package is available, we should compile with SSH. If there is no ssh package, we should compile w/o SSH support.

**Comment by smlng** [comment]
It's not a bug, it's hardly a feature. IMHO, RTRlib depending on `libssh` is not a big deal, as the `apt` tools will install any dependencies automatically. However, with PR #74 applied its possible to create deb-packages of RTRlib not relying on `libssh`.

**Comment by smlng** [comment]
Closing this one, is solved with #91 in place.
