### ISSUE TITLE
update/change init of structs

### ISSUE THREAD

**Issue by smlng** [rtrlib/rtrlib#77]
Hi all,

I started reviewing some of the code inclusions of `rtrlib` into BIRD, btw. latest branch on that is [int-new-bgpsec](https://github.com/CZ-NIC/bird/tree/int-new-bgpsec/proto/rpki). Though I haven't found any improvements so far, we may copy some coding style as an enhancement to `rtrlib`.

The coding style refers to initialization of structs, this is how we currently do it, for instance in `rtrlib/rtr/packet.c`:

```
    struct pdu_reset_query pdu;
    pdu.ver = rtr_socket->version;
    pdu.type = 2;
    pdu.flags = 0;
    pdu.len = 8;
``` 

and this is what it look likes in BIRD:
```
    struct pdu_reset_query pdu = {
        .ver = rtr_socket->version,
        .type = RESET_QUERY,
        .flags = 0,
        .len = 8,
   };
```
Btw. this also uses the enum/define for RESET_QUERY instead of the magic number.

However, what do you think @fho, @waehlisch is it worthwhile to adopt?

**Comment by fho** [comment]
Yes, I agree the initialization in BIRD is the better way.
But I think it's not worth to spend time on it:)

**Comment by smlng** [comment]
True indeed, but that was the only _interesting_ part I found in the BIRD RTR part, so far. We should put it on the list, anyway, for refactoring remaining code parts to comply with kernel coding style.

**Comment by smlng** [comment]
Not a real issue, closing.
