### ISSUE TITLE
No output from rtrclient

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#84]
There is no ROA output after starting rtrclient, even though connection to cache server was successfully established.

**Comment by nbars** [comment]
Passed `-p`? For me its working...

**Comment by smlng** [comment]
@waehlisch: confirmed @nbars! For me its working as well.

**Comment by smlng** [comment]
some output:

```
+ 2a05:4741:3::                               48 -  48       200983
+ 2a02:6840::                                 32 -  32       199255
+ 2404:f801:a808::                            48 -  48         8071
+ 2a01:4d0::                                  32 -  32        31400
+ 2a02:958::                                  32 -  32        29008
+ 2a03:66a0:1000::                            48 -  48       201214
+ 2001:980::                                  29 -  29         3265
+ 2a00:db8::                                  32 -  32         3058
+ 2a00:9380::                                 32 -  32        15557
+ 2a04:3800::                                 48 -  48        44417
+ 2a00:f680::                                 32 -  32        50171
+ 2620:117:b000::                             40 -  64        33011
+ 2803:9a00::                                 32 -  32       262239
+ 2001:67c:22dc::                             48 -  48        31019
+ 2a03:2880:f00a::                            48 -  48        32934
+ 2001:878::                                  29 -  48         1835
(2016/06/20 21:25:23:827896): RTR Socket: Sync successfull, received 23973 Prefix PDUs, 0 Router Key PDUs, session_id: 57403, SN: 52566
(2016/06/20 21:25:23:827945): RTR_MGR: Group(1) status changed to: RTR_MGR_ESTABLISHED
RTR-Socket changed connection status to: RTR_ESTABLISHED, Mgr Status: RTR_MGR_ESTABLISHED
(2016/06/20 21:25:23:827975): RTR Socket: State: RTR_ESTABLISHED
(2016/06/20 21:25:23:827979): RTR Socket: waiting 30 sec. till next sync
```

**Comment by waehlisch** [comment]
Strange, doesn't work for me:

mobi1:~/rpki/rtrlib-0.3.6/bin$ ./rtrclient tcp rpki-validator.realmv6.org 8282 -p
Prefix                                     Prefix Length         ASN
RTR-Socket changed connection status to: RTR_RESET, Mgr Status: 
RTR_MGR_CONNECTING
RTR-Socket changed connection status to: RTR_SYNC, Mgr Status: 
RTR_MGR_CONNECTING
RTR-Socket changed connection status to: RTR_FAST_RECONNECT, Mgr Status: 
RTR_MGR_CONNECTING
RTR-Socket changed connection status to: RTR_CONNECTING, Mgr Status: 
RTR_MGR_CONNECTING
RTR-Socket changed connection status to: RTR_RESET, Mgr Status: 
RTR_MGR_CONNECTING
RTR-Socket changed connection status to: RTR_SYNC, Mgr Status: 
RTR_MGR_CONNECTING
RTR-Socket changed connection status to: RTR_ESTABLISHED, Mgr Status: 
RTR_MGR_ESTABLISHED
RTR-Socket changed connection status to: RTR_SYNC, Mgr Status: 
RTR_MGR_ESTABLISHED


On Mon, 20 Jun 2016, Sebastian Meiling wrote:

> 
> some output:
> 
> + 2a05:4741:3::                               48 -  48       200983
> + 2a02:6840::                                 32 -  32       199255
> + 2404:f801:a808::                            48 -  48         8071
> + 2a01:4d0::                                  32 -  32        31400
> + 2a02:958::                                  32 -  32        29008
> + 2a03:66a0:1000::                            48 -  48       201214
> + 2001:980::                                  29 -  29         3265
> + 2a00:db8::                                  32 -  32         3058
> + 2a00:9380::                                 32 -  32        15557
> + 2a04:3800::                                 48 -  48        44417
> + 2a00:f680::                                 32 -  32        50171
> + 2620:117:b000::                             40 -  64        33011
> + 2803:9a00::                                 32 -  32       262239
> + 2001:67c:22dc::                             48 -  48        31019
> + 2a03:2880:f00a::                            48 -  48        32934
> + 2001:878::                                  29 -  48         1835
> (2016/06/20 21:25:23:827896): RTR Socket: Sync successfull, received 23973 Prefix PDUs, 0 Router K
> ey PDUs, session_id: 57403, SN: 52566
> (2016/06/20 21:25:23:827945): RTR_MGR: Group(1) status changed to: RTR_MGR_ESTABLISHED
> RTR-Socket changed connection status to: RTR_ESTABLISHED, Mgr Status: RTR_MGR_ESTABLISHED
> (2016/06/20 21:25:23:827975): RTR Socket: State: RTR_ESTABLISHED
> (2016/06/20 21:25:23:827979): RTR Socket: waiting 30 sec. till next sync
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[ABLTfHcWmIggl3W7E_KN4O4yL4dRSmUMks5qNuo0gaJpZM4I6A5s.gif]
> 
> 
> 


-- 
Dr. Matthias Waehlisch
.  Freie Universitaet Berlin, Inst. fuer Informatik, AG CST
.  Takustr. 9, D-14195 Berlin, Germany
.. mailto:waehlisch@ieee.org .. http://www.inf.fu-berlin.de/~waehl
:. Also: http://inet.cpt.haw-hamburg.de .. http://www.link-lab.net

**Comment by nbars** [comment]
The syntax is `./rtrclient tcp [options] <host> <port>`. The `-p` is at the wrong position.

**Comment by waehlisch** [comment]
Got it. Now it works. Seems like a too strict order of parameters.

On Mon, 20 Jun 2016, Nils Bars wrote:

> 
> The syntax is ./rtrclient tcp [options] <host> <port>. The -p is at the wrong position.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[ABLTfCV6EDq4zG5VcY6k1io0mbQirwxZks5qNxpsgaJpZM4I6A5s.gif]
> 
> 
> 


-- 
Dr. Matthias Waehlisch
.  Freie Universitaet Berlin, Inst. fuer Informatik, AG CST
.  Takustr. 9, D-14195 Berlin, Germany
.. mailto:m.waehlisch@fu-berlin.de .. http://www.inf.fu-berlin.de/~waehl
:. Also: http://inet.haw-hamburg.de .. http://www.link-lab.net
