### ISSUE TITLE
Byte order of an encapsulated erroneous pdu in an error pdu

### ISSUE THREAD

**Issue by shaddeus** [rtrlib/rtrlib#87]
RPKI-RTR could send an error PDU with encapsulated PDU from other side that was wrong. The function [`rtr_send_error_pdu()`](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L1110) expects an erroneous pdu in network byte order. The function is called correctly from function [`rtr_receive_pdu()`](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L428) where the pdu hasn't converted to host byte order yet. But all callings of [`rtr_send_error_pdu()`](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L1110) after the function [`rtr_receive_pdu()`](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L428) will send an error pdu with encapsulated errorneous pdu in host byte order.

Examples of incriminated places:
- Storing of prefix PDUs [packets.c:729](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L729)
- Storing of router keys [packets.c:761](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L761) 
- Handling of End of Data PDU [packets.c:920](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/rtr/packets.c#L920)
- some other places..

On this places the received pdu should be converted back to network byte order before sending an error pdu.

**Comment by fho** [comment]
Can we please ensure that a commit message describes what problem it fixes?
Also good would be if it would describe how the problem can be triggered and what it can cause. 

Nobody can know from a commit message like:

>  commit 65fddd7f77561f094954d7e688b4ef1a34e0446d
> Date:   Mon Dec 19 18:01:41 2016 +0100
> 
>     packets: fix byte order of encapsulated pdu
> 
>     fixes #87

What the problem is that was fixed.
To find it out you have to go to github, find the issue, read the whole thread thats cumbersome.

It also makes it much harder to e.g. compile a changelog.

**Comment by smlng** [comment]
while you already triggered that and referenced _changelog_: we could consider using [this](https://github.com/rafinskipg/git-changelog). If commit message have certain keywords, a changelog draft could be generated automatically.

I bet there are a bunch of similar tools out there, but this sounds nice in general.

**Comment by fho** [comment]
nice find, I can't imagine that it works so well in practise.
Often you still want to edit the changelog manually, you don't want to list every commit, you want to rewrite it a little bit for the user also we would have to embed their keywords in the commit messages

**Comment by smlng** [comment]
Sure, revising an auto generated changelog is most likely required. 

However, the point I wanted to make was (and from what you wrote, I think you'll agree), that if we encourage (enforce) usage of certain keywords and a certain style to our commit messages, we could use such tools to generate an initial changelog draft. Without going through the logs by hand
