### ISSUE TITLE
Shared-memory support for pfx_table struct

### ISSUE THREAD

**Issue by salsh** [rtrlib/rtrlib#95]
**Problem**
For optimization purposes, it would be necessary to be able to declare an instance of the struct `pfx_table` in the shared memory. Thus, different processes would have the possibility to share the same prefix table. Currently, however, this is not supported because the struct contains two `lpfst_node` pointers for IPv4 and IPv6. These point to the local heap, which is not available for other processes.

Transferring the pointers in the shared memory - in order to avoid changing the rtrlib code - does not work because the pointers are written to the heap again when adding or removing nodes.

**Possible solution**
A solution would be to pass an optional pointer (i.e., valid pointer for shared memory or NULL for local heap) to the corresponding functions. Thus, the functions - which modify the `lpfst_node` pointers - can save the pointers locally or shared. So the same rtrlib functions can be applied by changing the address range only. 

Since a reader/writer-lock is used to organise the access to the prefix table, it needs changes as follows: Based on the optional pointer, the reader/writer-lock will be initialized with the attribute `PTHREAD_PROCESS_SHARED` in order to be able to  modify the prefix table from different processes.

Can the above mentioned problem be solved? 

If so, what is your opinion concerning the solution proposed?

**Comment by fho** [comment]
Thanks for your suggestion!
In a scenario where multiple processes are using the RTRlib with the same RTR servers and the memory would be very very sparse it would give a benefit.

I don't know how much memory the pfx_table currently consumes. I would assume it is <1MB and in most usecases only 1-2 instances of the same pfx_table are kept in memory at the same time.
Additionaly sufficient amount of memory should be available on present hardware.
Therefore I think the benefit of the implementation is too small to realize it.
Do you agree? Are my assumptions correct?
